# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
  end
  
  #Define two VMs with static private IP addresses.
  boxes = [
    { :name => "web",
      :ip => "192.168.57.10",
    },
    { :name => "log",
      :ip => "192.168.57.15",
    },
    { :name => "vm3",
      :ip => "192.168.57.20",
    }
  ]
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
  
      config.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/*.conf
        systemctl restart sshd
      SHELL
        if opts[:name] == boxes.last[:name]
          config.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "ansible/provision.yml"
#	  ansible.inventory_path = "ansible/hosts"
#	  ansible.host_key_checking = "false"
            ansible.limit = "all"
          end
        end
   end  
end
end
