# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :"systemd-lab" => {
              :box_name => "ubuntu/jammy64",
              :box_version => "0",
              :cpus => 2,
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
     box.vm.provision "shell", inline: <<-SHELL
	mkdir -p ~root/.ssh
	cp ~vagrant/.ssh/auth* ~root/.ssh
       SHELL
     end 
    config.vm.provision "file", source: "./watchlog_files/", destination: "/tmp/"
    config.vm.provision "file", source: "./spawn-fcgi_files/", destination: "/tmp/"
    config.vm.provision "file", source: "./nginx_files/", destination: "/tmp/"
    
    config.vm.provision "shell", path: "provision_script.sh"
end
end
