# -*- mode: ruby -*-
# vi: set ft=ruby :
#home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"



MACHINES = {
  
  :frontngnx => {
      :box_name => "bento/ubuntu-22.04",
      :vm_name => "frontngnx",
      :cpus => 1,
      :memory => 1024,
      :net => [
                  #ip, adpter, netmask, virtualbox__intnet
                  ["192.168.56.100", 2, "255.255.255.0"], 
		  ["192.168.50.100", 3, "255.255.255.0"],
              ]  
  },

  :backend1 => {
      :box_name => "bento/ubuntu-22.04",
      :vm_name => "backend1",
      :cpus => 1,
      :memory => 1024,
      :net => [
                  ["192.168.50.101", 2, "255.255.255.0"],
              ]  
  },

  :backend2 => {
      :box_name => "bento/ubuntu-22.04",
      :vm_name => "backend2",
      :cpus => 1,
      :memory => 1024,
      :net => [
                  ["192.168.50.102", 2, "255.255.255.0"],
              ]  
  },

  :dbmaster => {
      :box_name => "bento/ubuntu-22.04",
      :vm_name => "bdmaster",
      :cpus => 1,
      :memory => 1024,
      :net => [
                  ["192.168.50.110", 2, "255.255.255.0"],
              ]  
  },
  
  :dbslave => {
      :box_name => "bento/ubuntu-22.04",
      :vm_name => "bdslave",
      :cpus => 1,
      :memory => 1024,
      :net => [
                  ["192.168.50.111", 2, "255.255.255.0"],
              ]  
  },

  :servermon => {
      :box_name => "bento/ubuntu-24.04",
      :vm_name => "servermon",
      :cpus => 3,
      :memory => 5120,
      :net => [
                  ["192.168.56.200", 2, "255.255.255.0"], 
		  ["192.168.50.200", 3, "255.255.255.0"],
              ]
  },

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      
      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2])
      end

      box.vm.provision "shell", inline: <<-SHELL
	    mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config.d/50-cloud-init.conf
        sudo systemctl restart sshd
      SHELL
    end
  end
end
