---
- name: Config frontngnx server
  hosts: frontngnx
  become: true
  tasks:
  - include_tasks: frontngnx/main.yml
  tags: frontngnx

- name: Config backend servers
  hosts: backend1,backend2
  become: true
  vars_files: backend/vars.yml
  tasks:
  - include_tasks: backend/main.yml
  tags: backend

- name: Config dbmaster server
  hosts: dbmaster
  become: true
  vars_files: dbmaster/vars.yml
  tasks:
  - include_tasks: dbmaster/main.yml
  tags: dbmaster

- name: Config dbslave server
  hosts: dbslave
  become: true
  vars_files: dbslave/vars.yml
  tasks:
  - include_tasks: dbslave/main.yml
  tags: dbslave

- name: Config servermon server
  hosts: servermon
  become: true
  tasks:
  - include_tasks: servermon/main.yml
  tags: servermon

- name: Config restore of dbmaster server
  hosts: dbmaster
  become: true
  vars_files: dbmaster/vars.yml
  tasks:
  - include_tasks: dbmaster/main_restore.yml
  tags: dbmaster_restore

...
