---
#- name: Time configuration
#  hosts: frontngnx
#  become: 'yes'

#  tasks:

- name: Set timezone
  shell:
    timedatectl set-timezone  Asia/Yekaterinburg

- name: timesync-status
  shell:
    timedatectl timesync-status
  register: results
- debug:
    var: results.stdout_lines

- name: print timedatectl
  shell:
    timedatectl
  register: results
- debug:
    var: results.stdout_lines

- name: print date
  shell:
    date
  register: results
- debug:
    var: results.stdout_lines

- name: Install base packages
  apt:
    name:
      - prometheus-node-exporter
    state: present
    update_cache: yes

- name: Set default routes
  shell:
    sudo ip route add default via 192.168.56.1 dev eth1

...
