
#- name: Time configuration
#  hosts: backend1,backend2
#  become: 'yes'

#  tasks:

- name: Set timezone
  shell:
    timedatectl set-timezone  Asia/Yekaterinburg

- name: timesync-status
  shell:
    timedatectl timesync-status
  register: results
- debug:
    var: results.stdout_lines

- name: print timedatectl
  shell:
    timedatectl
  register: results
- debug:
    var: results.stdout_lines

- name: print date
  shell:
    date
  register: results
- debug:
    var: results.stdout_lines

- name: Install base packages
  apt:
    name:
      - prometheus-node-exporter
    state: present
    update_cache: yes
...
