# -*- mode: ruby -*-
# vi: set ft=ruby :
#home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"



Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/jammy64"
	#config.vm.box_version = "20240801.0.0"

	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
        config.vm.synced_folder '.', '/vagrant', disabled: true

	config.vm.define "borgs" do |machine|
		machine.vm.network "private_network", ip: "192.168.57.160"
		machine.vm.hostname = "borgs"
		machine.vm.disk :disk, size: "2GB", name: "backup_disk"

                machine.vm.provision "shell", inline: <<-SHELL
                     mkdir -p ~root/.ssh
                     cp ~vagrant/.ssh/auth* ~root/.ssh
                SHELL
	end

	config.vm.define "borgc" do |machine|
		machine.vm.network "private_network", ip: "192.168.57.150"
		machine.vm.hostname = "borgc"

                machine.vm.provision "shell", inline: <<-SHELL
                     mkdir -p ~root/.ssh
                     cp ~vagrant/.ssh/auth* ~root/.ssh
                SHELL
        
                machine.vm.provision "ansible" do |ansible|
                     ansible.compatibility_mode = "2.0"
                     ansible.playbook = "ansible/provision.yml"
                     ansible.limit = "all"
                end
        end
end
