---
#- name: Iptables configuration on frontngnx server
#  hosts: frontngnx
#  become: 'yes'

#  tasks:

  - name: Allow traffic through loopback
    iptables:
      chain: INPUT
      in_interface: lo
      jump: ACCEPT

  - name: Allow ESTABLISHED,RELATED connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT

  - name: Drop INVALID connections
    iptables:
      chain: INPUT
      ctstate: INVALID
      jump: DROP

  - name: Allow SSH INPUT connections
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      ctstate: NEW
      jump: ACCEPT

  - name: Allow HTTPS INPUT connections
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 443
      jump: ACCEPT

  - name: Allow HTTP INPUT connections
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      jump: ACCEPT

  - name: Allow node exporter from prometheus
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 9100
      jump: ACCEPT

  - name: Allow ICMP
    iptables:
      chain: INPUT
      protocol: icmp
      jump: ACCEPT

  - name: DROP ALL on INPUT
    iptables:
      chain: INPUT
      policy: DROP
...
