---
#- name: Mine configuration frontngnx server
#  hosts: frontngnx
#  become: 'yes'

#  tasks:

- name: Install NGINX
  apt:
    name:
      - nginx
    state: present
    update_cache: true

- name: Copy filebeat deb-package
  copy:
    src: files/filebeat-8.9.1-amd64.deb
    dest: /tmp/filebeat-8.9.1-amd64.deb

- name: Install filebeat
  apt:
    deb: /tmp/filebeat-8.9.1-amd64.deb

- name: Start filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: started

- name: Create SSL directory in NGNX
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Copy config files NGINX and filebeat
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "templates/filebeat.yml.j2", dest: "/etc/filebeat/filebeat.yml" }
    - { src: "templates/default.j2", dest: "/etc/nginx/sites-available/default" }
    - { src: "templates/ca.crt.j2", dest: "/etc/nginx/ssl/ca.crt" }
    - { src: "templates/ca.key.j2", dest: "/etc/nginx/ssl/ca.key" }
  notify:
    - Reload NGINX
    - Restart filebeat

#handlers:
- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted
- name: Reload NGINX
  systemd:
    name: nginx
    state: reloaded

- name: Restart filebeat
  systemd:
    name: filebeat
    state: restarted

- include_tasks: frontngnx/preinstall.yml
- include_tasks: frontngnx/firewall.yml
...
